# Import Library

In [2]:
import tensorflow as tf

# Load Dataset

In [3]:
fashion_mnist  = tf.keras.datasets.fashion_mnist.load_data()

(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist
X_train, y_train = X_train_full[:-5000], y_train_full[:-5000]
X_valid, y_valid = X_train_full[-5000:], y_train_full[-5000:]

# Exploration if Dataset

In [4]:
X_train.shape, y_train.shape, X_valid.shape, y_valid.shape, X_test.shape, y_test.shape

((55000, 28, 28), (55000,), (5000, 28, 28), (5000,), (10000, 28, 28), (10000,))

In [5]:
X_train.shape[1:]

(28, 28)

In [6]:
X_train.dtype, y_train.dtype

(dtype('uint8'), dtype('uint8'))

In [7]:
X_train, X_valid, X_test = X_train / 255., X_valid / 255., X_test / 255.

In [8]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [9]:
class_names[y_train[0]], y_train[0]

('Ankle boot', 9)

# Creating the model using the sequential API

In [10]:
tf.random.set_seed(42)

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=X_train.shape[1:]),
    tf.keras.layers.Dense(300, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(10, activation="softmax")
])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [12]:
total_params = 784*300 + 300 + 300*100 + 100 + 100*10 + 10
print(total_params)

266610


In [13]:
model.layers

In [14]:
weights, biases = model.layers[1].get_weights()

In [15]:
weights

array([[ 0.05957338,  0.07356907, -0.02803523, ..., -0.05621241,
        -0.05450566,  0.02016473],
       [-0.00275242, -0.05572863, -0.01141461, ...,  0.03002854,
        -0.03067382,  0.05923694],
       [ 0.00923802, -0.01419082,  0.06117843, ..., -0.02370696,
         0.05524163, -0.04658846],
       ...,
       [-0.0070978 ,  0.01160976,  0.00349054, ..., -0.02032139,
         0.04093876,  0.06772634],
       [ 0.04780997, -0.00779437,  0.04959461, ...,  0.03402971,
         0.01941552, -0.0643885 ],
       [-0.00699031,  0.02272764,  0.01195957, ..., -0.06172654,
         0.00904441,  0.01548304]], dtype=float32)

In [16]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [17]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"]
              )

In [18]:
history = model.fit(X_train, 
                    y_train, 
                    epochs=10,
                    validation_data=(X_valid, y_valid)
                    )

Epoch 1/10
1719/1719 [==============================] - 7s 4ms/step - loss: 0.7232 - accuracy: 0.7634 - val_loss: 0.5057 - val_accuracy: 0.8294
Epoch 2/10
1719/1719 [==============================] - 8s 5ms/step - loss: 0.4892 - accuracy: 0.8299 - val_loss: 0.4601 - val_accuracy: 0.8350
Epoch 3/10
1719/1719 [==============================] - 7s 4ms/step - loss: 0.4428 - accuracy: 0.8454 - val_loss: 0.4235 - val_accuracy: 0.8494
Epoch 4/10
1719/1719 [==============================] - 7s 4ms/step - loss: 0.4180 - accuracy: 0.8537 - val_loss: 0.3980 - val_accuracy: 0.8612
Epoch 5/10
1719/1719 [==============================] - 7s 4ms/step - loss: 0.3970 - accuracy: 0.8607 - val_loss: 0.3910 - val_accuracy: 0.8604
Epoch 6/10
1719/1719 [==============================] - 7s 4ms/step - loss: 0.3808 - accuracy: 0.8663 - val_loss: 0.3934 - val_accuracy: 0.8580
Epoch 7/10
1719/1719 [==============================] - 7s 4ms/step - loss: 0.3683 - accuracy: 0.8692 - val_loss: 0.3713 - val_accuracy:

In [19]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.3769 - accuracy: 0.8682


[0.3769019842147827, 0.8682000041007996]

In [20]:
X_new = X_test[:3]
y_proba = model.predict(X_new)
y_proba.round(2)

1/1 [==============================] - 0s 195ms/step


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.07, 0.  , 0.15, 0.  , 0.77],
       [0.  , 0.  , 0.99, 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],
      dtype=float32)

In [33]:
import numpy as np
y_pred = y_proba.argmax(axis=-1)
y_pred

array([9, 2, 1], dtype=int64)

In [34]:
np.array(class_names)[y_pred]

array(['Ankle boot', 'Pullover', 'Trouser'], dtype='<U11')

In [35]:
y_proba.argmax(axis=1)

array([9, 2, 1], dtype=int64)

In [38]:
np.array(class_names)[y_test[:3]]

array(['Ankle boot', 'Pullover', 'Trouser'], dtype='<U11')

In [46]:
model.save(r"..\models\fashion-mnist-sequential-classifier.h5")