In [1]:
import torch
import numpy as np
torch.__version__

'2.2.1+cu121'

## Basics

In [2]:
scalar = torch.tensor(5)
scalar, scalar.ndim, scalar.item(), scalar.shape

(tensor(5), 0, 5, torch.Size([]))

In [3]:
vector = torch.tensor(data=[1, 2])
vector, vector.ndim, vector.shape

(tensor([1, 2]), 1, torch.Size([2]))

In [4]:
MATRIX = torch.tensor(
    [[7, 8], 
    [9, 10]]
    )
MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [12]:
TENSOR = torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6],
        ],
        [
            [9,9,9],
            [8,8,8],
        ]
    ]
)

TENSOR.shape

torch.Size([2, 2, 3])

In [11]:
MATRIX[0]

tensor([7, 8])

## Random Tensors

In [14]:
# Random tensor

RANDOM_TENSOR = torch.rand(size=(3,4))
RANDOM_TENSOR

tensor([[0.5772, 0.3558, 0.1131, 0.9588],
        [0.3646, 0.0748, 0.8008, 0.1414],
        [0.9427, 0.5194, 0.9533, 0.0433]])

In [15]:
RANDOM_TENSOR.ndim, RANDOM_TENSOR.shape

(2, torch.Size([3, 4]))

In [19]:
R1 = torch.rand(size=(2,3,4,2))
R1

tensor([[[[0.5974, 0.0812],
          [0.3828, 0.4458],
          [0.3735, 0.4341],
          [0.5339, 0.0607]],

         [[0.4669, 0.7763],
          [0.2252, 0.3594],
          [0.6416, 0.7339],
          [0.7574, 0.3931]],

         [[0.7008, 0.4932],
          [0.1199, 0.0562],
          [0.8932, 0.8829],
          [0.6064, 0.8964]]],


        [[[0.7506, 0.1110],
          [0.0544, 0.6348],
          [0.8424, 0.3067],
          [0.9742, 0.8348]],

         [[0.2342, 0.4704],
          [0.1156, 0.5002],
          [0.5754, 0.1273],
          [0.8222, 0.6269]],

         [[0.4684, 0.3933],
          [0.7675, 0.0972],
          [0.8641, 0.6183],
          [0.9963, 0.5300]]]])

In [20]:
R1.ndim, R1.shape

(4, torch.Size([2, 3, 4, 2]))

In [23]:
R2 = torch.rand(size=(3,224,224))
R2.shape, R2.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [24]:
R3 = torch.zeros(size=(3,3))
R3

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
R4 = torch.ones(size=(3,4), dtype=int)
R4

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

## Range of Tensors

In [28]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [31]:
R5 = torch.arange(1,10)
R5

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
torch.zeros_like(R5)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
torch.ones_like(R5)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
R5.zero_()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
R5.zero_() * torch.ones_like(R5)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
torch.arange(1,11,2) * torch.ones_like(R5)

RuntimeError: The size of tensor a (5) must match the size of tensor b (9) at non-singleton dimension 0

In [42]:
torch.Tensor([1,2]) * 2

tensor([2., 4.])

In [45]:
torch.Tensor([1,2]) * torch.Tensor([3,6])

tensor([ 3., 12.])

In [46]:
torch.Tensor([1,2]) * torch.Tensor([3])

tensor([3., 6.])

In [47]:
torch.Tensor([1,2]) * torch.Tensor([3, 6, 7])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0